server.port=8080
redis.cache.host=${REDIS_CACHE_HOST:redis-cache}
redis.cache.port=${REDIS_CACHE_PORT:6379}
spring.data.redis.host=${REDIS_CACHE_HOST:redis-cache}
spring.data.redis.port=${REDIS_CACHE_PORT:6379}
spring.data.redis.timeout=2000
