FROM gradle:8.7-jdk21 AS build
WORKDIR /app
COPY src/ .
RUN gradle jar --no-daemon -q
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
