apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: __FAULT_NAME__
  namespace: __NAMESPACE__
spec:
  action: delay
  mode: all
  selector:
    namespaces: [__NAMESPACE__]
    labelSelectors:
      app: postgres
  delay:
    latency: "500ms"
    correlation: "0"
    jitter: "0ms"
  duration: "__DURATION__"
