server.port=8080
server.address=0.0.0.0
spring.application.name=visa-application

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/vibe
spring.datasource.username=vibe
spring.datasource.password=vibe
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.validation-timeout=2000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.jakarta.persistence.query.timeout=2000

management.endpoints.web.exposure.include=health
