server.port=8080
spring.datasource.url=jdbc:postgresql://postgres:5432/vibe
spring.datasource.username=vibe
spring.datasource.password=vibe
spring.datasource.hikari.connection-timeout=2000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.data.redis.host=${REDIS_CACHE_HOST:redis-cache}
spring.data.redis.port=${REDIS_CACHE_PORT:6379}
spring.data.redis.timeout=2000
